spring:
  application:
    name: gn-tech
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5431/gn-tech-db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update